spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: ImageManagementService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: pwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
files:
  base-directory: "/img_upload/images"
  upload-extension: "png"
  subfolders:
    thumbnails: "/thumbnails"
    originals: "/originals"
