spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: ImageManagementService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: pwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
authorization:
  tokenHash: "$2y$10$Dw.wCpa.TEkG4OwmgfuU5e4xWIgQXtyJEFipZF0GoTcZhzK.4R5bC" # test password: test1234
files:
  base-directory: "/img_upload/images"
  upload-extension: "webp"
  validation:
    file-types: "image/png, image/jpg, image/jpeg, image/webp, image/gif"
    max-file-size: 30_000_000 # in bytes
  subfolders:
    thumbnails: "/thumbnails"
    originals: "/originals"